# Generated by Django 5.0.6 on 2024-05-28 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('release', models.DateField(blank=True, null=True, verbose_name='Release')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('finished_in', models.DateField(blank=True, null=True, verbose_name='Finished In')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Created In')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_profiles_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('finished_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_profiles_finished', to=settings.AUTH_USER_MODEL, verbose_name='Finished By')),
            ],
        ),
        migrations.CreateModel(
            name='TaskResponsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.taskprofile', verbose_name='Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='taskprofile',
            name='responsible',
            field=models.ManyToManyField(related_name='tasks_responsible', through='task.TaskResponsible', to=settings.AUTH_USER_MODEL),
        ),
    ]
