# Generated by Django 5.0.6 on 2024-05-30 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_taskprofile_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprofile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_profiles_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='taskprofile',
            name='created_in',
            field=models.DateTimeField(verbose_name='Created In'),
        ),
        migrations.AlterField(
            model_name='taskprofile',
            name='finished_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_profiles_finished', to=settings.AUTH_USER_MODEL, verbose_name='Finished By'),
        ),
        migrations.AlterField(
            model_name='taskresponsible',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.taskprofile', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='taskresponsible',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
