# Generated by Django 5.0.6 on 2024-05-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_taskprofile_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprofile',
            name='created_in',
            field=models.DateField(blank=True, null=True, verbose_name='Created In'),
        ),
        migrations.AlterField(
            model_name='taskprofile',
            name='updated',
            field=models.DateField(blank=True, null=True, verbose_name='Updated'),
        ),
    ]
