# Generated by Django 5.0.6 on 2024-06-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_taskprofile_created_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprofile',
            name='time',
            field=models.DateField(blank=True, null=True, verbose_name='Time'),
        ),
    ]
