# Generated by Django 5.0.6 on 2024-06-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_taskprofile_created_in_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskresponsible',
            unique_together={('task', 'user')},
        ),
    ]
